project_root: .

scan_include:
  - "**/*.liquid"
  - "**/*.html"
  - "**/*.js"
  - "**/*.ts"
  - "**/*.jsx"
  - "**/*.tsx"

scan_exclude:
  - "**/node_modules/**"
  - "**/.git/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/vendor/**"

css_include:
  - "assets/**/*.css"
  - "assets/**/*.css.liquid"
  - "assets/**/*.scss"
  - "assets/**/*.scss.liquid"

css_exclude:
  - "**/vendor/**"
  - "**/*.min.css"
  - "**/*.min.css.liquid"

allowlist:
  classes:
    - "is-active"
    - "is-open"
    - "hidden"
  ids: []

keep_regex:
  - "^swiper-"
  - "^splide"
  - "^tns-"
  - "^js-"
  - "^data-"
  - "^is-"
  - "^has-"

output_dir: ".liquidcss-scout-out"
mode: "safe"   
write_pruned_files: true
write_patches: true
write_html_report: true
